version: '3'

services:

  php:
    build: .docker/php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_DRIVER: "mysql"
      DATABASE_SERVER_VERSION: "5.7"
      DATABASE_URL: "mysql://root:root@mysql:3306/skeleton_db"
      MESSENGER_DSN: "amqp://rabbit:rq123456@queue:5672"
    command: bash -c "
                cd ./project &&
                composer install &&
                bin/console doctrine:database:create --if-not-exists &&
                bin/console doctrine:schema:update --force &&
                php -d variables_order=EGPCS -S 0.0.0.0:80 -t public"
    ports:
      - 81:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  adminer:
    image: adminer
    ports:
      - 82:8080
  queue:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rq123456"
    ports:
      - 15672:15672