version: '3'

services:

  php:
    build: .docker/php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      DATABASE_DRIVER: "pdo_sqlite"
      DATABASE_SERVER_VERSION: "3.15"
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/database.sqlite"
      MESSENGER_DSN: "amqp://rabbit:rq123456@queue:5672"
    command: bash -c "
                cd ./project &&
                composer install &&
                php -d variables_order=EGPCS -S 0.0.0.0:80 -t public"
    ports:
      - 81:80
  queue:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rq123456"
    ports:
      - 15672:15672